services:
  # 애플리케이션 서버
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server_container
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8 -Duser.timezone=Asia/Seoul
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    depends_on:
      - db

  # 웹 애플리케이션 서비스
  app:
    build:
      context: ./src/main/resources/static
      dockerfile: Dockerfile
    container_name: web_app_container
    ports:
      - "80:80"
    depends_on:
      - db

  # MySQL 데이터베이스 서비스
  db:
    image: mysql:8.0
    container_name: mysql_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_test_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_user_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: